### ISSUE TITLE
Typo in ICD10 to WBD10

### ISSUE THREAD

**Issue by git-cheryl** [cghr-toronto/icd#16]
data/icd10towbd10.csv

Road trafic accidents -> Road traffic accidents

We are using it to create standardized mortality maps for SL, please let me know when fixed!

**Comment by rrwen** [comment]
@git-cheryl Thanks - will update you when done! May need until end of week to sort out and clean up the code conversions to clear up confusion

**Comment by rrwen** [comment]
@git-cheryl Finished processing!

Data is now available at https://openmortality.org/dataset/icd

**Note**: `cghr10` are the BMC paper codes.

Closing now - solved by #15
